// backend/internal/server/frontend/src/pages/Login.tsx
import { useAuth } from "../components/Authentication";
import input from "../styles/Input.module.css"
import Button from "../styles/Button.module.css"
import Form from "../styles/Form.module.css"
import LoginStyles from "./Login.module.css"
import { useNavigate } from "react-router-dom";
import { useState } from "react";
import axios from "axios";



const Login = () => {
    type LoginForm = {
        username: string;
        password: string;
    }

    const [formData, setFormData] = useState<LoginForm>({
        username: '', 
        password: '',
    })

    const { login } = useAuth()
    const navigate = useNavigate()

    const handleLogin = async (e: React.FormEvent) => {
        e.preventDefault()

        try {
            const response = await axios.post("http://localhost:8080/user/login", formData)

            if (response.status == 200){
                login()
                navigate("/search")
            }
        } catch (error) {

            console.log(error)
        }
    }

    const handleValueChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const {name, value} = e.target;

        setFormData((prev) => ({
            ...prev,
            [name]: value,
        }))

    }

    return (
        <form onSubmit={handleLogin} className={Form.default} action="">
            <h1>Login</h1>
            <div className={LoginStyles.input_container}>
                <input 
                    placeholder=" "
                    name="username" 
                    onChange={handleValueChange}
                    type="text" 
                    value={formData.username} 
                    className={`${input.default} ${LoginStyles.input}`}
                />
                <label className={LoginStyles.label}>Username</label>
            </div>
            <div className={LoginStyles.input_container}>
                <input 
                    placeholder=" "
                    name="password" 
                    onChange={handleValueChange} 
                    type="password" 
                    value={formData.password}
                    className={`${input.default} ${LoginStyles.input}`}
                />
                <label className={LoginStyles.label}>Password</label>
            </div>
                <button type="submit" className={`${Button.default} ${LoginStyles.button_login}`}>Login</button>
        </form>

    )
}

export default Login;

// frontend/src/routes/(public)/login/+page.svelte
<script lang="ts">
	import { goto } from "$app/navigation";
	import { onMount } from "svelte";


    type LoginForm = {
        username: string,
        password: string,
    }

    onMount(() => {
        goto("/login", {replaceState: false, keepFocus: true})
    })



    let form: LoginForm = $state({username: "", password: ""})

    const onsubmit = async (e: SubmitEvent) => {
        e.preventDefault()
        
        const res = await fetch('http://localhost:8000/api/user/login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(form)
        });
        if (res.status == 200) {
            goto("/", {invalidateAll: true})
        }


    }
</script>


<form onsubmit={(e) => onsubmit(e)} action="login">
    <label for="username">username</label>
    <input type="text" id="username" bind:value={form.username}>
    <label for="password">password</label>
    <input type="password" id="password" bind:value={form.password}>
    <button type="submit">Login</button>
</form>

<style></style>
